/**
 * TugProgressPulsingDot — Internal building block for the breathing-dot glyph.
 *
 * App code should use {@link TugProgressIndicator} instead.
 *
 * The glyph **breathes** — the inner dot scales up and down on a continuous
 * 2s cycle, and the ring is emitted from that breath rather than clocked on
 * its own. It supersedes an earlier dot of the same name that held a fixed
 * circle and chained one-shot WAAPI ring pulses around it; that one was a
 * blinker with a halo, and this one is a thing that inhales and exhales.
 *
 * Two visible elements on ONE shared 2s period:
 *
 *   - **Dot** — a solid circle that rises to full size and sinks back
 *     over the cycle, traveling the full swing every time. Its color
 *     resolves from the parent's live `--tugx-progress-indicator-fill`.
 *   - **Ring** — fired a few degrees before the top of the breath, so it
 *     is already alive and moving when the dot turns. It is born at the
 *     dot's own edge and expands outward to the glyph box, fading as it
 *     goes — so the exhale is one gesture: the dot falls away from the
 *     ring it just shed. Below 28px it is let out past the box; see
 *     {@link sizeGeometry}.
 *
 * **The envelope is not symmetric.** The dot rises over the first 30% of
 * the cycle and sinks over the remaining 70% — quick in, slow out, the
 * shape of the colon blink on an Apple Watch digital time label. A breath
 * that takes as long going up as coming down reads as a mechanism; this
 * one reads as something alive. The whole curve, both legs and the ring's
 * ignition, lives in the stops of the stylesheet's `@keyframes` blocks and in
 * one `cubic-bezier()` per segment, generated by {@link breathKeyframes} —
 * never in a multi-stop `linear()` easing, which WebKit cannot hand to the
 * compositor, and never in more stops than the shape needs, which WebKit
 * re-samples once each on every compositing update. The
 * gallery's timing bench injects alternative keyframe blocks and points
 * the `--…-*-name` variables at them to show cuts side by side.
 *
 * **One clock, by construction.** Both elements run CSS `@keyframes` on the
 * same duration, and every start goes through `startLoops`, which assigns
 * every loop under the root one identical `startTime`. The weld is therefore
 * a fact about the animations rather than a hope about the order two
 * attribute writes happened to land in: whichever loop was already running,
 * and whichever frame each was created on, all of them afterwards read the
 * same clock at the same offset. No timer, no WAAPI chaining, no per-frame
 * main-thread work. Every dot in the app runs that same duration unless its
 * caller opts into a jitter ({@link dotDriftFor}), which only the Cards
 * card's session list does. Firing near the turn also keeps the ring inside a
 * single cycle, so the pulse needs no wrap across the cycle boundary.
 *
 * The loops stay CSS and stay gated on `data-breathing` / `data-emitting`,
 * which is what keeps their `@keyframes` — and the `--…-*-name` override hooks
 * the gallery's benches point at them — the source of the curve. A
 * `CSSAnimation` IS a WAAPI `Animation`: its `startTime` is settable and its
 * `currentTime` readable, so the weld costs the keyframes nothing.
 *
 * Opening a gate that is already open still starts nothing, and that used to
 * be this file's one unrecoverable bug — a glyph that started its two loops a
 * quarter cycle apart shed rings out of the breath for as long as it ran, with
 * no clock to re-sync against and no cycle boundary to recover on. It is now
 * simply a no-op: the `startTime` write that follows re-welds whatever is
 * there. The dance that used to stand in for a clock — delete both gates,
 * force a reflow, re-open them in the same style flush — is gone with the
 * reason for it, and so is the forced layout it cost.
 *
 * Work RESUMING while the last settle's pulse is still travelling — the
 * ordinary way work resumes, since a pulse is in the air for most of a cycle —
 * is no longer a special case in the motion, only in the pose. The ring is
 * spoken for and the pulse always finishes, so the breath is welded to the
 * FLYING RING rather than started on a clock of its own. That puts the breath
 * somewhere on the fall while the settled dot sits on the presence ladder, and
 * the well absorbs the difference: pinned at the ratio of the two, released to
 * 1 on the settle transition, so the dot glides into a breath that was already
 * running at the right phase.
 *
 * **Two treatments.** The glyph serves both a 28px Cards card row and a 10px status
 * cell, and it does that by carrying two geometries rather than scaling one —
 * see {@link BIG_SIZE}. The motion below is common to both; the proportions,
 * the ring's reach, and the PRESENCE ladder are not.
 *
 * **No state change is a cut.** The glyph's state changes when the work does,
 * on a frame nobody chose, with the dot somewhere in the middle of a breath and
 * possibly a ring in mid-flight. Letting CSS gate the loops on `data-state`
 * made that arrival a tear: the ring vanished wherever it happened to be and
 * the dot jumped to its resting pose. So the motion is gated on two attributes
 * this component writes — `data-breathing` and `data-emitting` — and every
 * arrival is a CROSSING instead:
 *
 *   - A lit pulse **always finishes its travel**. It was shed; it is leaving
 *     under its own momentum, and the work ending is no business of its. The
 *     emitter is released on the pulse's clock, not the state's ({@link
 *     releaseEmitter}). A pulse that was never lit is simply not lit.
 *   - The dot **is caught where it stands**: its live scale is pinned inline,
 *     the loop is dropped against that pin, and a CSS transition carries it
 *     from there to the settled pose. Entering `running` is the same idea
 *     inverted — the loop starts at the phase whose pose the dot already holds
 *     ({@link breathPhaseFor}), so the breath picks it up mid-stride.
 *   - The static ring **fades**, and the tint **crosses**, on that same
 *     duration, so the whole arrival reads as one gesture.
 *
 * **Every crossing is written on a WELL, never on the figure that breathes.**
 * WebKit decides acceleration over an element's whole effect stack, so a dot
 * whose keyframes share a box with a `transform` transition and a
 * `background-color` transition is demoted to main-thread ticking for the
 * length of any crossing — the disqualifying form the animation doctrine's
 * qualifying form exists to forbid, and the glyph used to hold it
 * structurally. Each figure now sits inside a well that owns the position,
 * the centering translate, the crossing pose and the tint; the figure carries
 * its keyframes and nothing else. The painted pose is the product of the two,
 * which is what lets a crossing pin one and drop the other in a single style
 * flush. Every inline `style.transform` / `style.transition` write below —
 * and every inline-pose READ — is the well's.
 *
 * State semantics, each rung also carrying its own PRESENCE — its share of the
 * reserved box ({@link SETTLED_PRESENCE}), so at the big end the glyph's SIZE
 * reads the state before its color or motion does:
 *   running   — the dot breathes and emits rings; owns the whole box.
 *   paused    — dot held at full size; static outer ring, drawn in.
 *   stopped   — quiet (reduced) dot; small static ring.
 *   completed — quiet dot; small static ring, success tint from parent.
 *   aborted   — full-size dot; static outer ring drawn in, danger tint.
 *
 * **Settled states render settled DOM — the end-state swap.** Progress
 * machinery is for progress. A dot that has reached an end state and is not
 * mid-crossing renders in **static mode**: same spans, same box, same visible
 * circles, but the dot is sized by width/height instead of a transform,
 * centered by `inset`/`margin` instead of a translate, and carries **no
 * `transition` and no animation attributes** — so it holds no stacking
 * context, no compositing layer, and no retained `CSSTransition`. That is not
 * a nicety: a restored transcript mounts one of these per historical tool
 * call, and a few hundred settled-but-live dots were measured at 82% of a
 * heavy card's composited breadth, walked twice per keystroke. A dot born
 * settled is static from its first render and no motion machinery ever runs.
 *
 * The **live↔static handoff never cuts** ({@link armDemotion}):
 *   - static→live promotion happens synchronously in the crossing layout
 *     effect, before the crossing plays — the live DOM's first frame is
 *     seeded to the exact pose the static DOM was painting;
 *   - live→static demotion follows the RULE: **swap when settled.** The
 *     glyph demotes only once everything under it has come to rest — the
 *     settle transition done (`transitionend`, with a resolved-duration
 *     fallback), no pulse in flight (`data-emitting` released on the pulse's
 *     own clock), nothing else animating under the root, and one frame of
 *     grace — so the swap replaces DOM that has painted its final pose with
 *     DOM that paints the identical pose. A new state during the window
 *     abandons the demotion; the machine stays live for the new crossing.
 *     Late is free, early is a glitch: static mode is a cost optimization
 *     with no deadline.
 *
 * Laws: [L02] state arrives via props from the parent indicator;
 *       [L06] tone is a live CSS variable, and the crossing between states is
 *       CSS transitions driven by DOM attributes and one inline pose — the
 *       state currently on screen is a ref, never React state, so a crossing
 *       renders nothing. The render MODE (static | live) is React state
 *       deliberately: it is a STRUCTURE change (different DOM contract), which
 *       is exactly what renders are for; appearance within a mode still never
 *       renders;
 *       [L13] the breath and the ring are continuous loops, so they are
 *       declarative CSS `@keyframes` (motion-off zeroes them through the
 *       global `body[data-tug-motion="off"]` rule, which zeroes the settle's
 *       transitions with them — the demotion's duration fallback reads the
 *       RESOLVED duration, so motion-off collapses the settle window to ~0
 *       rather than stalling it). The script here starts and releases those
 *       loops and hands off between them; it never drives a frame.
 *
 * @module components/tugways/internal/tug-progress-pulsing-dot
 */

import "./tug-progress-pulsing-dot.css";

import React from "react";

import { cn } from "@/lib/utils";
import { acquireMotionHold } from "@/lib/motion-guard/registry";
import { observeOffscreen } from "@/lib/motion-guard/offscreen";
import type {
  TugProgressIndicatorShape,
  TugProgressIndicatorState,
} from "../tug-progress-indicator";

/**
 * Glyph box diameter when the caller names no size. Sized against the Z5
 * submit button (36px square) — this glyph is meant to be legible across
 * the room the way that button is. It runs a little under, since motion
 * carries some of the load that size alone carries for a static control.
 */
const DEFAULT_SIZE = 32;

/**
 * Dot diameter as a fraction of the glyph box, at the top of the breath.
 *
 * At the big end the dot IS the object being looked at, so it takes most of the
 * box and the remainder is the room the emitted ring expands into. At the small
 * end it is {@link SMALL_DOT_RATIO} instead — the previous glyph's ratio, kept
 * so a settled marker in a status row is the size it has always been.
 */
const DOT_RATIO = 0.6;

/** The small treatment's dot ratio — the previous glyph's, unchanged. */
const SMALL_DOT_RATIO = 0.5;

/**
 * Trough of the breath — the dot's scale at the bottom of the cycle. A
 * wide swing on purpose: the dot travels the full distance every cycle,
 * and the ring's emission is a waypoint on the way down, not the end of
 * the fall. Mirrors `--tugx-progress-pulsing-dot-dot-scale-min`.
 */
const DOT_SCALE_MIN = 0.35;

/**
 * How far before the turn the ring is lit, as a fraction of the cycle —
 * **ignition advance**, borrowed from a spark engine. The turn is top dead
 * center; the spark fires a few degrees before it, so the pressure is already
 * building when the piston turns. Read the cycle as 360°, 3% is **10.8°
 * BTDC** — a plausible advance for a real engine, and the same reasoning
 * applies here. The ring needs a few frames to become visible and start
 * moving; lighting it exactly at the turn means the eye catches it slightly
 * late, trailing the dot.
 */
const EMIT_ADVANCE = 0.03;

/** Turn of the shipped envelope — the CSS defaults are `breathEnvelope(0.3)`. */
export const DEFAULT_BREATH_TURN = 0.3;

/**
 * The size band across which this glyph changes what it is trying to be.
 *
 * There are two treatments here, not one figure scaled. At {@link BIG_SIZE} and
 * up — the Cards card session row — it is a figure meant to be read across a room:
 * the dot takes 60% of the box, the ring stays inside it, and the PRESENCE
 * ladder encodes state as relative size. At {@link SMALL_SIZE} and down — a Z2
 * status cell, a tool-call header, a setup step — it is a marker in a row of
 * type, and every one of those choices is wrong for it: relative size is not
 * legible in 12 pixels, and a bigger dot is just a bigger dot.
 *
 * **The small treatment is the previous glyph's geometry, exactly.** Same 0.5
 * dot ratio, same full-box static ring, same hairline stroke, no ladder — so a
 * settled dot in a status cell paints the pixels it painted before. What
 * changes down there is the MOTION and nothing else: the dot breathes and sheds
 * a ring instead of holding still under a halo. That is the whole point of
 * unifying the variants, and it is the whole extent of it.
 *
 * The band is chosen to sit in the gap between the real call sites: everything
 * the app asks for is 16px and under or 28px and over, so nothing ships at a
 * blend. The ramp between exists so the in-between sizes a gallery or a future
 * caller might pick degrade smoothly rather than snapping at a threshold.
 */
const BIG_SIZE = 28;
const SMALL_SIZE = 16;

/** 0 at {@link BIG_SIZE} and up, 1 at {@link SMALL_SIZE} and down. */
function smallness(size: number): number {
  return Math.min(1, Math.max(0, (BIG_SIZE - size) / (BIG_SIZE - SMALL_SIZE)));
}

/**
 * How far past the glyph box a small ring travels.
 *
 * Layout-safety is a luxury of size. Held inside the box, the ring's whole
 * journey is from the dot's edge to the box edge — at a 32px glyph that is
 * 6.5px of radius and reads as a pulse; at 12px it is 2.5px and reads as a
 * twitch, a ring that appears, shivers, and stops. There is no timing fix for
 * that: the distance simply is not there.
 *
 * So below {@link BIG_SIZE} the ring is let out of the box, ramping to
 * this multiple at {@link SMALL_SIZE} and under. It is not a new idea —
 * it is what the glyph this one replaces always did (its ring ran to 1.9× the
 * box), and it is why that glyph read at 12px at all. Overflow is free here:
 * the ring is absolutely positioned and nothing on the path clips, so a bigger
 * reach costs paint, never layout.
 */
const REACH_MAX = 1.75;

/**
 * The small treatment's trough — a much shallower breath than the big one's.
 *
 * Depth of breath does not survive being scaled down, because the bottom of the
 * swing is where the dot is least able to spare anything. {@link DOT_SCALE_MIN}
 * takes a 19.2px dot down to 6.7px, which still reads as a dot; the same ratio
 * takes a 6px dot down to 2.1px, which reads as a dot going out. And unlike the
 * big glyph, the small one is sitting in a row of type where it is the only
 * mark: it cannot afford to half-disappear on every cycle.
 *
 * So the swing narrows as the glyph shrinks, to this at {@link SMALL_SIZE} and
 * under. The amplitude it gives up at the bottom it takes back at the top, where
 * there are pixels to spend — see {@link SMALL_PEAK}.
 */
const SMALL_TROUGH = 0.7;

/**
 * The small treatment's peak — the dot grows PAST its own diameter at the top of
 * the breath, and the ring is shed off that swollen edge.
 *
 * The big glyph tops out at 1: at 32px the dot is already 19px and the box's
 * remaining 40% is the ring's runway, so growing the dot would only eat the
 * distance the pulse has to travel. Small, both of those facts invert. A 6px dot
 * held to its own diameter at the top of a shallow trough barely moves at all —
 * the swing is under three pixels of diameter, which the eye reads as a static
 * mark that a ring happens to leave. And the runway is not in the box anyway;
 * {@link REACH_MAX} already sends the ring outside it.
 *
 * So the small dot swells instead. At 1.5 a 6px dot runs 4.2px → 9px, a swing
 * you cannot miss, and the ignition catches it near the top — so the ring
 * springs from a dot that is visibly at its largest, which is the gesture.
 */
const SMALL_PEAK = 1.5;

/** The big treatment's peak — the dot's own diameter, unchanged. */
const DOT_SCALE_MAX = 1;

/**
 * The glyph box that paints a dot of `diameterPx`.
 *
 * The dot is a fraction of its box ({@link sizeGeometry}), so a caller who
 * knows what the mark must MEASURE — an atom's register does, since a live pill
 * and a Canvas bake have to show the same dot — states the diameter and gets
 * the box back. Inverted inside the small band, where the ratio is flat; a
 * diameter that would put the box above {@link SMALL_SIZE} is clamped there,
 * because past that point the ratio moves with the size and there is no single
 * inverse.
 */
export function markBoxForDot(diameterPx: number): number {
  return Math.min(SMALL_SIZE, Math.round(diameterPx / SMALL_DOT_RATIO));
}

/**
 * The furthest diameter the whole mark ever paints, for a glyph box of
 * `boxPx` — the ring at the end of its travel, not the dot.
 *
 * The ring is let out of the box below {@link BIG_SIZE} ({@link REACH_MAX}),
 * and that overflow is free only where nothing bounds the mark. Inside an
 * enclosure it is not free at all: a caller that sized its dot by the dot
 * alone gets a ring crossing the wall around it a moment later, which is what
 * a session atom's pill did. So the envelope is published, and a bounded
 * caller sizes against this rather than against the diameter it wanted.
 *
 * `reach` is that caller's own cap — the multiple it publishes as
 * `--tugx-progress-pulsing-dot-emit-reach` because its enclosure will not hold
 * the automatic one. It only ever shortens the travel: a cap above what the
 * size already asks for is not a longer pulse, it is a caller measuring
 * against a ring the glyph will never paint.
 */
export function markRingEnvelope(boxPx: number, reach?: number): number {
  const auto = sizeGeometry(boxPx).reach;
  return boxPx * (reach === undefined ? auto : Math.min(reach, auto));
}

/**
 * Everything about the glyph that cannot be one number across a 10px–40px
 * range, derived from the size in one place.
 *
 * The timing is untouched by any of it — the envelope, the ignition advance and
 * the stroke weights are scale-free and every size gets the same breath. What
 * changes is geometry, because each of these is a ratio against a box that is
 * no longer one size:
 *
 *   - **ratio** — the dot's share of the box. 0.6 big, 0.5 small (the previous
 *     glyph's), so a settled small dot is the size it always was.
 *   - **reach** — where the ring's expansion ends. The box edge at the big end,
 *     and out past it at the small end, where the box is not far enough away to
 *     be worth traveling to.
 *   - **scaleMin** — the trough of the breath. A deep swing at the big end, a
 *     shallow one at the small end, where the dot cannot spare the pixels at the
 *     bottom.
 *   - **scaleMax** — the top of the breath. The dot's own diameter at the big
 *     end, and past it at the small end, where the amplitude has to come from
 *     somewhere and the top is where the pixels are.
 *   - **birth** — where the dot's edge is when the spark fires. Falls out of
 *     the other three; it is here so it cannot drift from them.
 *
 * All five are published as `-auto` variables so an override from above still
 * wins (see the stylesheet's note on the knobs), and all five resolve to the
 * stylesheet's own defaults at {@link BIG_SIZE} and up.
 */
export function sizeGeometry(size: number): {
  ratio: number;
  reach: number;
  scaleMin: number;
  scaleMax: number;
  birth: number;
} {
  const t = smallness(size);
  const ratio = DOT_RATIO + (SMALL_DOT_RATIO - DOT_RATIO) * t;
  const scaleMin = DOT_SCALE_MIN + (SMALL_TROUGH - DOT_SCALE_MIN) * t;
  const scaleMax = DOT_SCALE_MAX + (SMALL_PEAK - DOT_SCALE_MAX) * t;
  const atIgnition = breathAt(
    DEFAULT_BREATH_TURN,
    DEFAULT_BREATH_TURN - EMIT_ADVANCE,
  );
  return {
    ratio,
    reach: 1 + (REACH_MAX - 1) * t,
    scaleMin,
    scaleMax,
    // Where the dot's edge actually is when the spark fires. It moves with the
    // ratio and both ends of the swing, so it is derived here rather than left
    // to the stylesheet's big-size default — otherwise a small ring is born
    // inside the dot it is supposed to be peeling off.
    birth: ratio * (scaleMin + (scaleMax - scaleMin) * atIgnition),
  };
}

/**
 * Exponent of the ring's opacity falloff — 1 is an even fade, and every step
 * up front-loads it harder.
 *
 * Shipped even. The pulse's problem was never the shape of its exit, it was
 * that it was born at partial strength: a ring that starts pre-faded and then
 * dims uniformly reads as grey. Fix the birth (see `--…-emit-opacity`) and the
 * even fall is the one that reads as a ring travelling outward and thinning.
 * Front-loading on top of that mostly shortens the ring's visible life, which
 * costs more than the extra snap buys.
 */
export const DEFAULT_FADE_POWER = 1;

/**
 * Shipped pulse stroke weight, mirroring the fallback on
 * `--tugx-progress-pulsing-dot-pulse-weight`.
 *
 * It is the weight the pulse ENDS at, as a multiple of the resting ring's — not
 * the weight it carries throughout. The stroke opens across the ring's travel,
 * from a 1px hairline at ignition to this as the ring reaches the box and fades
 * out: sharp where it is brightest, soft where it is leaving. The stylesheet
 * pre-divides both ends by the scale they paint at, since a border on a
 * `transform: scale`d element renders at border × scale.
 *
 * Read it as an intent rather than a rendered ratio: borders resolve to device
 * pixels, so at the sizes this glyph runs at (a 28px Cards card row, a 32px bench
 * cell) neighboring weights can paint identically.
 */
export const DEFAULT_PULSE_WEIGHT = 1.6;

/**
 * The breath's shape at progress `p`, for a cycle that turns at `turn`.
 *
 * Each leg is its own cosine ease-in-out, fitted to its own length rather than
 * one curve skewed across the turn. That is the part that matters: a cosine
 * arrives at its endpoint with zero velocity, so however quick the rise, it
 * settles into a HOLD at the top instead of hitting a corner, and the long
 * fall then drifts away from that hold. Rise, hover, sink.
 */
export function breathAt(turn: number, p: number): number {
  return p <= turn
    ? (1 - Math.cos(Math.PI * (p / turn))) / 2
    : (1 + Math.cos(Math.PI * ((p - turn) / (1 - turn)))) / 2;
}

/**
 * The cosine ease-in-out {@link breathAt} describes, as the one form Core
 * Animation can accelerate: a cubic bezier.
 *
 * Both legs of the breath use it. The rise runs `(1 - cos(pi*u)) / 2` and the
 * fall runs its mirror, so one symmetric bezier serves both — the fall's
 * keyframe interpolates downward, which turns `bezier(u)` into `1 - bezier(u)`
 * for free. Agreement with {@link breathAt} is within 0.002 over either leg,
 * asserted in `breath-keyframes.test.ts` rather than trusted.
 */
const BREATH_LEG_EASING = "cubic-bezier(0.37, 0, 0.63, 1)";

/**
 * The cubic ease-out `1 - (1 - u)**3` the ring's radius used to be sampled
 * from, as a bezier. Agreement is within 0.003, asserted alongside the breath's.
 */
const EXPAND_EASING = "cubic-bezier(0.33, 1, 0.68, 1)";

/** Trim a computed stop to something readable in a stylesheet. */
function stop(n: number): string {
  const s = n.toFixed(4).replace(/0+$/, "").replace(/\.$/, "");
  return s === "" || s === "-0" ? "0" : s;
}

/**
 * The whole envelope for a given turn, as the three `@keyframes` blocks the
 * stylesheet carries — three stops and a bezier per leg, not a sampled curve.
 *
 * **Two separate rules govern this block, and conflating them is what produced
 * the shape this replaced.**
 *
 * The first is QUALIFICATION. Core Animation expresses a segment's easing as a
 * cubic bezier, so a multi-stop `linear()` or a `steps()` is not one, and
 * WebKit answers by declining to accelerate the animation at all — blending it
 * on the main thread, every element, every frame. On a 100-glyph bench that
 * was 18.0% of the main thread against 0.9%. That rule is real and this file
 * is where it was learned. A per-segment `cubic-bezier()` does not trip it: it
 * is exactly the form Core Animation already speaks.
 *
 * The second is PRICE PER KEYFRAME, and it applies to animations that already
 * qualified — which is why sampling the curve into stops, the fix for the
 * first rule, did nothing for this one. WebKit rebuilds its layer-overlap map
 * from scratch on every compositing update, and for each layer carrying a
 * running transform animation it re-derives the box that layer can reach by
 * sampling the animation once per keyframe, allocating a style per sample,
 * with no cache across updates. An accelerated 21-stop loop is still billed 21
 * samples per dot per compositing update. Measured on the release deck at a
 * fixed population of 23 dots, the sampled form cost a mean of 22.0 samples of
 * `computeExtentOfTransformAnimation` per three-second process sample and this
 * form cost 5.7 — 0.26x, the two distributions not overlapping.
 *
 * Hence three stops and two, with the shape in a `cubic-bezier()` per segment:
 * it qualifies under the first rule and it is cheap under the second. The turn
 * survives as the knob — hand this a different one and the dot's legs, the
 * ring's ignition and the radius it is born at all still move together.
 *
 * `breathKeyframes(DEFAULT_BREATH_TURN, "tugx-progress-pulsing-dot")` is what
 * the stylesheet's blocks were generated from; regenerate them together if the
 * turn changes.
 *
 *   - **breathe** — the dot. Three stops: trough at 0%, peak at the turn,
 *     trough at 100%, each leg eased by {@link BREATH_LEG_EASING}. The legs
 *     are eased separately rather than by one curve skewed across the turn,
 *     which is what gives the hold at the top: a cosine arrives at its
 *     endpoint with zero velocity, so however quick the rise, it settles
 *     instead of hitting a corner.
 *   - **expand** — the ring's radius. Two stops: parked at birth radius
 *     through the inhale (the ring unlit at the dot's edge), then out to the
 *     box edge under {@link EXPAND_EASING}.
 *   - **fade** — the ring's opacity, on a keyframe that runs lit → 0. Held at
 *     1 (i.e. invisible) through the inhale, stepped to 0 in a hairline
 *     between two stops at the same position, then a power falloff back to 1
 *     ({@link DEFAULT_FADE_POWER}, shipped even). The ring is at nearly full
 *     strength for the frames it is still on the dot's edge, then thins evenly
 *     as it travels. Radius and opacity are separate animations because their
 *     HOLDS are opposite (radius parked at 0, opacity parked at 1) and because
 *     their shapes are specified independently.
 *   - **emit-birth** — the dot's own scale at ignition × {@link DOT_RATIO}, so
 *     the ring peels off the dot's edge rather than appearing beside it.
 */
export function breathKeyframes(turn: number, prefix: string): string {
  const ignition = turn - EMIT_ADVANCE;
  const TROUGH = "var(--tugx-progress-pulsing-dot-trough-resolved)";
  const PEAK = "var(--tugx-progress-pulsing-dot-peak-resolved)";
  const BIRTH = "var(--tugx-progress-pulsing-dot-birth-resolved)";
  const REACH = "var(--tugx-progress-pulsing-dot-reach-resolved)";
  const pose = (scale: string): string =>
    // `scale()` alone: the centering translate lives on the figure's WELL, so
    // the keyframes carry one transform function instead of two and the
    // compositor interpolates a scale rather than a two-function list.
    `    transform: scale(${scale});`;
  const ease = (curve: string): string =>
    `    animation-timing-function: ${curve};`;

  // Three stops, two legs, one bezier per leg. The rule-level
  // `animation-timing-function: linear` in the stylesheet is what a segment
  // gets when its stop declares nothing; the declarations below override it
  // for the segment that STARTS at that stop, which is why the final stop of
  // each block carries none.
  const breathe = [
    `  0% {\n${ease(BREATH_LEG_EASING)}\n${pose(TROUGH)}\n  }`,
    `  ${stop(turn * 100)}% {\n${ease(BREATH_LEG_EASING)}\n${pose(PEAK)}\n  }`,
    `  100% {\n${pose(TROUGH)}\n  }`,
  ];

  const expand = [
    `  0%,\n  ${stop(ignition * 100)}% {\n${ease(EXPAND_EASING)}\n${pose(BIRTH)}\n  }`,
    `  100% {\n${pose(REACH)}\n  }`,
  ];

  const fade = [
    `  0%,\n  ${stop(ignition * 100 - 0.01)}% {\n    opacity: 0;\n  }`,
    `  ${stop(ignition * 100)}% {\n    opacity: var(--tugx-progress-pulsing-dot-emit-opacity, 0.95);\n  }`,
    `  100% {\n    opacity: 0;\n  }`,
  ];

  return [
    `@keyframes ${prefix}-breathe {\n${breathe.join("\n")}\n}`,
    `@keyframes ${prefix}-emit-expand {\n${expand.join("\n")}\n}`,
    `@keyframes ${prefix}-emit-fade {\n${fade.join("\n")}\n}`,
  ].join("\n\n");
}

/**
 * Half-width of the period jitter, as a fraction of the nominal 2s cycle.
 *
 * The point is a column of them. Several sessions breathing on one exact
 * period read as one mechanism with several heads; give each its own rate and
 * they pull apart over half a minute or so into something that reads as
 * several things each doing its own work. At ±4% the widest pair differs by
 * ~160ms per cycle, so neighbors take roughly a dozen breaths to fall out of
 * step — slow enough that no single glance catches the drift happening.
 *
 * It only ever scales the period, so every loop under one draw still reads
 * the same duration and stay phase-locked: the ring is still shed at 10.8° BTDC
 * of that breath.
 */
const DRIFT_SPREAD = 0.04;

/**
 * The jitter for one item, as the style that carries it — spread `key` over
 * `[1 - DRIFT_SPREAD, 1 + DRIFT_SPREAD]` and pin it.
 *
 * **Drift is opt-in, and almost nothing opts in.** It is not a property of the
 * glyph and not a property of the indicator either; it is a property of a LIST
 * OF ITEMS, and the only such list is the Cards card's session rows. Every other
 * pulsing dot in the app runs the nominal period, locked — which is what the
 * Z2 STATE cell needs, since it renders two separate indicators flanking one
 * label and they have to read as one status. Automatic drift, at either level,
 * had that pair breathing against each other.
 *
 * So the caller names the item and gets its rate:
 *
 *     <TugProgressIndicator variant="pulsing-dot" style={dotDriftFor(cardId)} />
 *
 * Keyed rather than drawn, because identity is what the jitter is supposed to
 * track. A random draw per mount would re-roll a session's rate every time the
 * Cards card filtered, scrolled it out and back, or hot-reloaded; hashing the id
 * means a session breathes at its own rate for as long as it exists, and two
 * rows never collide by accident of timing. It also needs no state, so it
 * survives every remount for free.
 */
export function dotDriftFor(key: string): React.CSSProperties {
  // FNV-1a, 32-bit. Any cheap avalanche would do — what matters is that
  // neighboring ids (`card-1`, `card-2`) land far apart rather than adjacent.
  let hash = 0x811c9dc5;
  for (let i = 0; i < key.length; i++) {
    hash ^= key.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  const unit = (hash >>> 0) / 0x100000000;
  const drift = 1 + (unit * 2 - 1) * DRIFT_SPREAD;
  return {
    ["--tugx-progress-pulsing-dot-drift" as string]: drift.toFixed(4),
  } as React.CSSProperties;
}

/**
 * Cycle position where the ring is lit — the frame a pulse begins to exist.
 * Before it, the ring is parked and fully faded and there is nothing to finish.
 */
const IGNITION = DEFAULT_BREATH_TURN - EMIT_ADVANCE;

/**
 * Slack on the emitter's release, in ms.
 *
 * A late release is free and an early one is not, so the timer is deliberately
 * generous. The ring reaches opacity 0 at the end of its travel and stays there
 * for the next 27% of the following cycle, so dropping the animation anywhere in
 * that window paints identically; cutting it a frame EARLY clips the tail of a
 * visible pulse, which is the whole thing being avoided.
 */
const EMIT_RELEASE_SLACK = 32;

/**
 * Resolve pending style on `el`'s document, so the write just made is the pose
 * a crossing starts FROM rather than one coalesced away with it.
 *
 * `getAnimations()` rather than `void el.offsetWidth`, and the difference is
 * layout. Both resolve style; `offsetWidth` additionally forces a layout pass
 * this file never wanted — the poses here are transforms, which layout does
 * not inform. Measured on the release deck over 2000 iterations against a
 * dirtied layout: `offsetWidth` 39ms, `getComputedStyle(el).transform` 40ms,
 * `getAnimations()` 19ms, an empty loop 1ms. So the read is real — it is not
 * optimized away — and it is half the price, because it stops at style.
 *
 * **It is a real flush on an element with nothing to report, which was the one
 * thing worth checking.** A fast path for "no animations here" would have made
 * the first-paint seed tear: the pose would coalesce with the pose after it and
 * the crossing would fire from the old one. Probed directly on the deck —
 * write `transition: none` and a pose, flush, release the transition and write
 * another pose, then read the resulting `CSSTransition`'s first keyframe. With
 * `getAnimations()` it reads the seeded pose, with `offsetWidth` it reads the
 * same, and with no flush at all it reads the pose before the seed. The two
 * flushes are interchangeable here; the absence of one is what tears.
 *
 * `getComputedStyle(el).transform` is NOT an alternative: at 40ms it forces
 * layout exactly as `offsetWidth` does. That matters beyond this helper —
 * {@link liveScale} reads it, so the settle pin and the hand-back still force
 * layout after every `offsetWidth` in this file is gone.
 */
function flushStyle(el: HTMLElement): void {
  el.getAnimations();
}

/**
 * The DOT-WELL's transform at a given crossing scale.
 *
 * The well owns the centering translate and the crossing pose in one list;
 * the dot inside it owns the breath and sits at `scale(1)` whenever the
 * breath is not running. Painted pose is the product of the two, which is why
 * the crossing arithmetic below can pin one and drop the other in the same
 * flush without the eye seeing anything move.
 *
 * Transforms interpolate componentwise only between matching lists, so the
 * well's every pose is written in this one shape; anything else would
 * decompose to a matrix mid-settle.
 */
function dotPose(scale: number): string {
  return `translate(-50%, -50%) scale(${scale})`;
}

/**
 * The scale an element is painting at RIGHT NOW — the animated value, not the
 * declared one.
 *
 * This is the whole mechanism behind a smooth exit. A state change arrives on
 * an arbitrary frame, with the dot at an arbitrary point in its breath, and the
 * only way out that does not jump is to start the settle from the pose actually
 * on screen. `getComputedStyle` resolves animations, so it reports that pose;
 * the caller pins it inline before dropping the loop, and the removal becomes a
 * no-op the eye cannot see.
 *
 * Read the DOT on the running→settled crossing — the breath's scale, with the
 * well standing at 1 — and the WELL on the settled→running one, where the
 * settled pose lives on the well and the dot sits at 1. One function either
 * way, so the `none` and parse guards stay in one place.
 */
function liveScale(el: HTMLElement): number | null {
  const value = getComputedStyle(el).transform;
  if (!value || value === "none") return null;
  try {
    return new DOMMatrixReadOnly(value).a;
  } catch {
    return null;
  }
}

/**
 * Where a loop on `el` is in its cycle right now, and how long that cycle is —
 * `null` when nothing is looping there.
 *
 * Read off the running animation rather than tracked, for the same reason
 * {@link liveScale} is: the loop is the authority on where the loop is, and
 * anything the script remembers instead would drift the moment a duration, a
 * drift factor or a motion setting changed underneath it.
 *
 * Called on the DOT to read the breath and on the RING to read a pulse still
 * in the air. All three loops share one duration, so either reading is a
 * reading of the same cycle — which is the whole premise of the weld.
 */
function breathClock(el: HTMLElement): { phase: number; period: number } | null {
  for (const animation of el.getAnimations()) {
    if (!(animation instanceof CSSAnimation)) continue;
    const period = animation.effect?.getComputedTiming().duration;
    if (typeof period !== "number" || period <= 0) continue;
    // `currentTime` is the clock the weld writes, so it is the clock the weld
    // is read back through. `getComputedTiming().progress` is the same number
    // one indirection later and it was the phase source [P04] removed.
    const current = animation.currentTime;
    const ms = typeof current === "number" ? current : 0;
    return { phase: (((ms % period) + period) % period) / period, period };
  }
  return null;
}

/**
 * The weld itself: every `CSSAnimation` under `root` is given one identical
 * `startTime` — `document.timeline.currentTime - phase × period` — so all of
 * them read the same clock at the same offset ([P04]), whichever frame each
 * was created on.
 *
 * `getAnimations()` is both halves of the job: the call resolves style, which
 * is what CREATES the animations the gates (or the stylesheet) just declared,
 * and it hands back the objects to weld. So there is no flush here separate
 * from the read, and no forced layout anywhere in it ([P03]).
 *
 * `period` is read from the effect rather than assumed, so
 * `--tugx-progress-pulsing-dot-drift` and any `--tug-timing` scaling are
 * honoured without this function knowing either exists. Computed timing, not
 * specified: `getTiming().duration` is `number | "auto" | undefined` and would
 * need a cast at every read.
 *
 * Under the breaker's demotion, or off screen, there is nothing to weld. Zero
 * iterations give each effect no active duration and no fill, so the
 * animations are not relevant and `getAnimations()` does not return them at
 * all — the early return is the contract exactly as it stands.
 *
 * Two callers: `startLoops`, which sets the gates and then welds; and the
 * off-screen return, which welds a figure whose loops the stylesheet just
 * re-declared, so a dot scrolled back into view resumes through the same
 * weld it started with rather than at whatever phase each loop happened to be
 * created on.
 */
function weldLoops(root: HTMLElement, phase: number): void {
  const loops = root
    .getAnimations({ subtree: true })
    .filter((a): a is CSSAnimation => a instanceof CSSAnimation);
  let period = 0;
  for (const loop of loops) {
    const duration = loop.effect?.getComputedTiming().duration;
    if (typeof duration === "number" && duration > 0) {
      period = duration;
      break;
    }
  }
  if (period <= 0) return;
  const now = document.timeline.currentTime;
  const shared = (typeof now === "number" ? now : 0) - phase * period;
  for (const loop of loops) loop.startTime = shared;
}

/**
 * Where on the breath's RISE leg the dot would be standing at `scale` —
 * the inverse of {@link breathAt}, restricted to the leg that has one.
 *
 * Used to start the loop at the phase that matches the pose already on screen,
 * which `startLoops` then writes as the loops' shared `startTime`, so entering
 * `running` picks the settled dot up rather than snapping it to the trough. The
 * rise is the right leg to invert on: a glyph that starts working should be on
 * its way up.
 *
 * Clamped just short of {@link IGNITION} so the loop never begins inside a
 * pulse. Only one pose in the ladder reaches that clamp — a `paused` dot at the
 * small treatment, which sits at full scale — and there the clamp costs about a
 * thousandth of the dot's diameter. Past it the cost would be a ring appearing
 * from nowhere at near-full opacity, which is the pop this function exists to
 * avoid, arriving by another door.
 */
function breathPhaseFor(
  scale: number,
  scaleMin: number,
  scaleMax: number,
): number {
  const span = scaleMax - scaleMin;
  const value =
    span <= 0 ? 0 : Math.min(1, Math.max(0, (scale - scaleMin) / span));
  const phase = (DEFAULT_BREATH_TURN * Math.acos(1 - 2 * value)) / Math.PI;
  return Math.max(0, Math.min(phase, IGNITION - 0.005));
}

/**
 * The scale the breath paints at `phase` — {@link breathPhaseFor}'s forward
 * direction, over the whole cycle rather than the rise alone.
 *
 * For one caller: a resume that finds the last settle's pulse still in the air
 * welds the breath to the flying ring, which means the breath starts at a phase
 * whose pose the dot is NOT standing at. There is no painted pose to read
 * there — the breath has not begun — so the pose has to be computed, and the
 * well then absorbs the discrepancy ([P05]).
 *
 * It is deliberately NOT what the running→settled pin uses. That pin's whole
 * job is exactness, and this arithmetic is inexact twice over: it carries the
 * bezier's fit error against the cosine, and it is blind to a
 * `--tugx-progress-pulsing-dot-dot-scale-min` / `-max` override, which the
 * resolved-variable chain admits from above and the component never sees. The
 * pin keeps {@link liveScale}.
 */
function breathScaleAt(
  phase: number,
  scaleMin: number,
  scaleMax: number,
): number {
  return (
    scaleMin + (scaleMax - scaleMin) * breathAt(DEFAULT_BREATH_TURN, phase)
  );
}

/**
 * Stop emitting — but not before the pulse in flight has finished flying.
 *
 * **Once a pulse is lit it always completes.** It is a thing the glyph shed: it
 * left the dot, it is travelling outward under its own momentum, and the work
 * ending has no bearing on it. Cutting it mid-travel is the most visible tear a
 * state change can make, because the eye is already tracking a moving object.
 *
 * So the emitter is released on the pulse's clock rather than the state's. The
 * animation keeps running to the end of its current iteration and the attribute
 * is dropped after it, by which point the ring has faded to nothing and there
 * is nothing left to see go. A pulse that was never lit — the change landed
 * during the inhale, before {@link IGNITION} — is dropped immediately; there is
 * no gesture in progress to honor, and holding the gate open would only let one
 * more ring out of a glyph that has already stopped working.
 */
function releaseEmitter(
  root: HTMLElement,
  ring: HTMLElement,
  timer: React.MutableRefObject<number | null>,
  onReleased?: () => void,
): void {
  if (timer.current !== null) {
    window.clearTimeout(timer.current);
    timer.current = null;
  }
  let remaining = 0;
  for (const animation of ring.getAnimations()) {
    // Keyframe loops only: a transition's progress has nothing to do with
    // where the pulse is, and counting one held the emitter open on a glyph
    // that never lit a ring.
    if (!(animation instanceof CSSAnimation)) continue;
    // The breath runs on the dot span whenever the glyph runs; only the
    // ring's own loops say anything about whether a pulse is in flight.
    const timing = animation.effect?.getComputedTiming();
    const progress = timing?.progress;
    const duration = typeof timing?.duration === "number" ? timing.duration : 0;
    if (typeof progress !== "number" || duration <= 0) continue;
    if (progress < IGNITION) continue;
    remaining = Math.max(remaining, (1 - progress) * duration);
  }
  if (remaining <= 0) {
    delete root.dataset.emitting;
    onReleased?.();
    return;
  }
  timer.current = window.setTimeout(() => {
    timer.current = null;
    delete root.dataset.emitting;
    onReleased?.();
  }, remaining + EMIT_RELEASE_SLACK);
}

/** Settled states paint a reduced dot; held / canceled keep it full-size. */
function isQuiet(state: TugProgressIndicatorState): boolean {
  return state === "stopped" || state === "completed";
}

const IDLE_DOT_SCALE = 0.85;

/**
 * How far a quiet state draws the dot in, at this size.
 *
 * It ramps out with {@link smallness} for the same reason the PRESENCE ladder
 * does, and it was an oversight that it did not: below {@link SMALL_SIZE} the
 * glyph says its state with tone and with whether the ring is moving, because
 * a fraction of a dot that is already four pixels across is not a quieter mark
 * — it is a blurrier one. A 0.85 there asks for 3.4px of dot, which is neither
 * a whole device pixel at 1x nor at 2x, and a small circle off the device grid
 * is snapped onto it by the compositor a half pixel away from the ring it is
 * supposed to sit inside. So the small treatment keeps the whole dot, and the
 * big treatment — where 15% is a visible ~2.5px and the geometry is coarse
 * enough to absorb it — is unchanged.
 */
function quietScale(state: TugProgressIndicatorState, size: number): number {
  if (!isQuiet(state)) return 1;
  return IDLE_DOT_SCALE + (1 - IDLE_DOT_SCALE) * smallness(size);
}

/**
 * The PRESENCE ladder — how much of the reserved glyph box each state
 * occupies.
 *
 * Size is this variant's whole argument: it exists to be read across a room.
 * But "big" is only legible as a signal if it is *relative*, and the earlier
 * cut had it backwards — every settled state painted a full-box static ring,
 * so a finished session drew a bigger figure than a working one. A row of
 * sessions read as loudest where nothing was happening.
 *
 * So presence became a property of the state, not a constant. `running` is
 * absent from the ladder because it has no static pose to scale: its breath
 * and its emitted ring are authored against the full box and own it outright
 * (see {@link presenceScale}). Every other state is a pose the component seeds,
 * and each one draws in from that edge by the amount below — a held or aborted
 * session stays substantial because it still wants an answer; a stopped or
 * completed one recedes to a quiet marker.
 *
 * The box itself never changes, so the ladder is pure appearance: rows do not
 * reflow as a session moves through it, and a caller's `size` still means the
 * space to reserve.
 *
 * These are the values at full strength. Below 28px the ladder compresses
 * toward 1, and by 16px it is gone — see {@link presenceScale}.
 */
const SETTLED_PRESENCE: Record<
  Exclude<TugProgressIndicatorState, "running">,
  number
> = {
  paused: 0.7,
  aborted: 0.7,
  stopped: 0.5,
  completed: 0.5,
};

/**
 * This state's share of the glyph box, at this size.
 *
 * The ladder ({@link SETTLED_PRESENCE}) is an affordance of the big treatment,
 * and only of it. It encodes state as *relative* size, which needs enough
 * pixels for the relation to be visible — a `completed` 12px glyph on the full
 * ladder is a 6px ring around a 2.5px dot, which is not a quiet marker but an
 * illegible one. So the ladder ramps out with {@link smallness}: gone entirely
 * at 16px and below, where every state owns its box exactly as it did under the
 * previous glyph, and the difference between states is carried by tone and by
 * whether the ring is moving. Those two read at 10px. Size does not.
 */
function presenceScale(state: TugProgressIndicatorState, size: number): number {
  if (state === "running") return 1;
  const base = SETTLED_PRESENCE[state];
  return base + (1 - base) * smallness(size);
}

/**
 * The scale a settled dot rests at — the presence rung, quieted further for
 * the quiet states. `running` resolves to 1 (full box), which is also the
 * pose a promotion seeds a crossing INTO running from.
 */
function settledScaleFor(
  state: TugProgressIndicatorState,
  size: number,
): number {
  return quietScale(state, size) * presenceScale(state, size);
}

/**
 * Slack on the demotion's duration fallback, in ms. The fallback exists for
 * a `transitionend` that never comes — a zero-duration settle (motion-off
 * resolves the duration to 0) or a settled→settled change that lands on an
 * identical pose (no computed change, no transition, no event). Generous for
 * the same reason {@link EMIT_RELEASE_SLACK} is: a late swap is free.
 */
const DEMOTE_SETTLE_SLACK = 80;

/**
 * The settle duration as the engine resolved it, in ms — never the authored
 * token. Under motion-off (or any `--tug-timing` scaling) the resolved value
 * is what actually elapses, so the demotion window collapses or stretches
 * with it instead of guessing.
 *
 * Read off the DOT-WELL, which is where the settle transition lives. Its
 * declared list is `transform, color` in that order, so the first
 * comma-segment is still the transform settle the demotion is waiting on.
 */
function resolvedSettleMs(well: HTMLElement): number {
  const first = getComputedStyle(well).transitionDuration.split(",")[0].trim();
  const value = Number.parseFloat(first);
  if (!Number.isFinite(value)) return 0;
  return first.endsWith("ms") ? value : value * 1000;
}

export interface TugProgressPulsingDotProps {
  /** Glyph box diameter in CSS px. @default 32 */
  size?: number;
  /** Lifecycle state. @default "running" */
  state?: TugProgressIndicatorState;
  /**
   * The mark's shape. `dot` is the circle; `diamond` is the same glyph turned
   * 45°, for a caller that needs two readings to share one tint. Geometry
   * only — the breath, the pulse, and the crossings are identical, and the
   * pulse takes the mark's shape with it.
   * @default "dot"
   */
  shape?: TugProgressIndicatorShape;
  /** When true, opacity dims. */
  disabled?: boolean;
  /** Additional CSS class names. */
  className?: string;
}

export const TugProgressPulsingDot = React.forwardRef<
  HTMLSpanElement,
  TugProgressPulsingDotProps
>(function TugProgressPulsingDot(
  {
    size = DEFAULT_SIZE,
    state = "running",
    shape = "dot",
    disabled = false,
    className,
  },
  forwardedRef,
) {
  // The two treatments and everything derived from the size ([sizeGeometry]).
  const { ratio, reach, scaleMin, scaleMax, birth } = sizeGeometry(size);
  // The dot's box is its settled diameter; the breath scales it from there —
  // down at every size, and up past it at the small treatment ([SMALL_PEAK]),
  // where the swell paints outside the box the way the ring already does.
  const dotSizePx = size * ratio;
  // The state's share of the box ([SETTLED_PRESENCE]). Published as a variable
  // so the static ring can size itself from it in CSS without a second source
  // of truth — and so it sizes by WIDTH rather than a transform, which keeps
  // the ring's stroke the same weight at every rung of the ladder.
  const presence = presenceScale(state, size);
  // The period jitter is NOT drawn here — it belongs to the item, and one item
  // can render two glyphs. See [dotDriftFor].
  // The pose the dot rests at once it has settled, drawn in by the state's
  // presence. In live mode it is written to the DOM by the controller below
  // rather than rendered, because a state change has to CROSS to it from
  // wherever the breath left the dot — and React cannot see that pose, only
  // this one. In static mode the SAME number renders as a width/height
  // factor through the `--…-static-scale` variable, a channel with no
  // transform and no transition.
  const staticScale = settledScaleFor(state, size);

  const rootStyle: React.CSSProperties = {
    ["--tugx-progress-pulsing-dot-size" as string]: `${size}px`,
    ["--tugx-progress-pulsing-dot-dot-size" as string]: `${dotSizePx}px`,
    ["--tugx-progress-pulsing-dot-presence" as string]: `${presence}`,
    ["--tugx-progress-pulsing-dot-static-scale" as string]: `${staticScale}`,
    ["--tugx-progress-pulsing-dot-emit-reach-auto" as string]: `${reach.toFixed(4)}`,
    ["--tugx-progress-pulsing-dot-dot-scale-min-auto" as string]: `${scaleMin.toFixed(4)}`,
    ["--tugx-progress-pulsing-dot-dot-scale-max-auto" as string]: `${scaleMax.toFixed(4)}`,
    ["--tugx-progress-pulsing-dot-emit-birth-auto" as string]: `${birth.toFixed(4)}`,
  };

  // The render mode — the end-state swap. STRUCTURE, so it is React state
  // (see the module header's [L06] note): static renders settled DOM, live
  // renders the loop-and-crossing DOM. Born settled → static, so a restored
  // transcript's dots never touch the motion machinery at all — and the
  // crossing effect's first-paint branch reads that pairing the other way
  // round: live at mount means running.
  const [mode, setMode] = React.useState<"static" | "live">(() =>
    state === "running" ? "live" : "static",
  );

  const rootRef = React.useRef<HTMLSpanElement | null>(null);
  const dotRef = React.useRef<HTMLSpanElement | null>(null);
  const ringRef = React.useRef<HTMLSpanElement | null>(null);
  // The wells. Every inline pose write and every inline pose READ below is
  // the well's, not the figure's — see the CSS's well comment for why the
  // figure may carry no transition at all.
  const dotWellRef = React.useRef<HTMLSpanElement | null>(null);
  const ringWellRef = React.useRef<HTMLSpanElement | null>(null);
  // The state currently ON SCREEN, which lags the prop for as long as the
  // crossing takes. Held in a ref, not state: it is read to decide what the
  // crossing IS, and it must never provoke a render [L06].
  const shownRef = React.useRef<TugProgressIndicatorState | null>(null);
  const emitTimerRef = React.useRef<number | null>(null);
  // The pending live→static demotion, if one is armed. Cancelling abandons
  // the window; the effect re-arms when appropriate.
  const demotionRef = React.useRef<{ cancel(): void } | null>(null);
  // Where work blocked on a pulse in flight parks its continuation — a pending
  // demotion, which is the only thing that parks here now: a resume mid-pulse
  // welds the breath to the flying ring rather than waiting for it. The emitter
  // release invokes it (see releaseEmitter's onReleased).
  const emitReleasedRef = React.useRef<(() => void) | null>(null);
  // The motion hold ([D7], [P02]). It spans LIVE MODE, not `data-breathing`:
  // the emitter outlives the breath by design — `releaseEmitter` lets a lit
  // pulse finish its travel after the attribute is deleted — so a hold tied
  // to the attribute would disarm the render-cost probe with the ring still
  // animating. Live mode is the predicate this component already tracks, and
  // it is the one the registry wants. The release closure is idempotent, which
  // is what lets the two paths that must carry it — the static-mode demotion
  // and the unmount cleanup — each call it without knowing about the other.
  const motionHoldRef = React.useRef<(() => void) | null>(null);
  // The off-screen watch rides the same span as the hold: a live figure is
  // watched, a static one is not, and the release is carried by the same two
  // paths. Off screen the stylesheet stills the loops; back on screen the
  // figure re-welds them itself (`weldLoops`), so the return is the dot's own
  // start-time weld rather than three loops created on three frames.
  const offscreenRef = React.useRef<(() => void) | null>(null);

  const setRootRef = React.useCallback(
    (node: HTMLSpanElement | null) => {
      rootRef.current = node;
      if (typeof forwardedRef === "function") forwardedRef(node);
      else if (forwardedRef)
        (
          forwardedRef as React.MutableRefObject<HTMLSpanElement | null>
        ).current = node;
    },
    [forwardedRef],
  );

  /**
   * Cross to `state` from whatever is on screen, and run the end-state swap.
   *
   * There are three crossings and each is smooth for its own reason:
   *
   *   - **into a settled state** — the breath is caught in the act. Its live
   *     scale is pinned inline, the loop is dropped against that pin so the
   *     removal changes nothing, and the transition then runs from there.
   *     Meanwhile the shed pulse finishes on its own clock ({@link
   *     releaseEmitter}) and the static ring fades in over it.
   *   - **into `running`** — the loop starts at the phase whose pose the dot is
   *     already standing at ({@link breathPhaseFor}). The breath picks the dot
   *     up mid-stride. If the settle's own pulse is still in the air the
   *     breath is welded to the flying ring instead and the well absorbs the
   *     pose difference ({@link breathScaleAt}).
   *   - **between two settled states** — a plain property change; the dot's
   *     CSS transition carries it, along with the ring's diameter and the tint.
   *
   * Static mode adds the bookends. A state change arriving on a static glyph
   * promotes it to live FIRST (the setState flushes and this effect re-runs
   * before the frame paints), and the live pass seeds the dot's inline pose
   * to exactly what the static DOM was painting — so the crossing starts
   * from there, indistinguishable from a crossing between two live poses.
   * Every crossing that lands in a settled state arms a demotion, which
   * fires only when the full settled predicate holds ({@link armDemotion}):
   * swap when settled, never before.
   *
   * A layout effect, so the DOM is correct before the frame is painted: run
   * after paint and every crossing would show one frame of the wrong pose,
   * which is the tear in miniature.
   */
  React.useLayoutEffect(() => {
    const root = rootRef.current;
    const dot = dotRef.current;
    const ring = ringRef.current;
    const well = dotWellRef.current;
    const ringWell = ringWellRef.current;
    if (!root || !dot || !ring || !well || !ringWell) return;

    // Any effect run supersedes a pending demotion: a newer state abandons
    // the window (re-armed below when still appropriate), and a completed
    // demotion's own run clears the spent machinery.
    demotionRef.current?.cancel();
    demotionRef.current = null;
    emitReleasedRef.current = null;

    const previous = shownRef.current;
    const isRunning = state === "running";

    if (mode === "static") {
      // Settled: the render IS the pose and nothing is ticking. Drop the hold
      // before the bookkeeping, so a deck whose last live glyph just settled
      // disarms the probe in the same commit that stills it.
      motionHoldRef.current?.();
      motionHoldRef.current = null;
      offscreenRef.current?.();
      offscreenRef.current = null;
      // Static mode has no script: the render IS the settled pose. What
      // happens here is arrival bookkeeping and the exit.
      if (well.style.transform !== "") {
        // Just demoted from live: strip the live-mode inline machinery
        // before this frame paints. [data-static] already declares
        // `display: contents` and `transition: none` on the well, so the
        // strip changes no computed value and can fire nothing.
        well.style.transform = "";
        well.style.transition = "";
      }
      if (state === "running" || (previous !== null && state !== previous)) {
        // A crossing arrived on a static glyph. Promote: the live pass
        // right after this render plays the crossing, seeded from the
        // static pose. `shownRef` deliberately keeps the OLD state so
        // that pass knows what it is crossing from.
        setMode("live");
        return;
      }
      shownRef.current = state;
      return;
    }

    shownRef.current = state;

    // Live mode from here down — loops, crossings, or both. One hold for the
    // whole of it, taken once and kept across every re-run of this effect.
    if (motionHoldRef.current === null) {
      motionHoldRef.current = acquireMotionHold();
    }
    if (offscreenRef.current === null) {
      offscreenRef.current = observeOffscreen(root, (visible) => {
        // Only a breathing figure has loops to weld; a crossing in flight
        // has its own choreography and is left to it.
        if (visible && root.dataset.breathing !== undefined) weldLoops(root, 0);
      });
    }

    /**
     * Start the breath and the emitter, and WELD them — which is a thing done
     * to the animations, not a thing hoped for from the order of two writes.
     *
     * The gates go on, and then `weldLoops` gives every `CSSAnimation` under
     * the root one identical `startTime`. That is the lock, expressed as
     * data: whatever frame each loop happened to be created on, and whichever
     * of them was already running, all three are afterwards reading the same
     * clock at the same offset ([P04]).
     *
     * Writing a gate that is already set still starts nothing, and that is now
     * harmless rather than the file's one unrecoverable bug: the weld is
     * applied to whatever is there afterwards, so a loop that kept running is
     * re-welded exactly like one that just began. The old dance — delete both
     * gates, force a reflow, re-open them in the same flush — existed only to
     * make the two starts coincide, and goes with the reason for it.
     */
    const startLoops = (phase: number): void => {
      if (emitTimerRef.current !== null) {
        window.clearTimeout(emitTimerRef.current);
        emitTimerRef.current = null;
      }
      root.dataset.breathing = "";
      root.dataset.emitting = "";
      weldLoops(root, phase);
    };


    /**
     * Arm the live→static demotion — the SWAP WHEN SETTLED rule. All
     * clauses required, in order:
     *
     *   1. state agreement — guaranteed by construction: any newer state
     *      re-runs this effect, which cancels the pending window first
     *      thing;
     *   2. the dot's settle transition has completed — `transitionend`
     *      for `transform`, with a resolved-duration fallback for the
     *      events that never come (motion-off resolves the duration to 0;
     *      an identical-pose change fires no transition at all);
     *   3. no pulse in flight — `data-emitting` absent. A lit ring always
     *      finishes its travel on its own clock; the emitter release
     *      re-invokes the check however long after the dot landed;
     *   4. nothing else animating under the root — catches the static
     *      ring's fade and the tint crossings, which run their own
     *      transitions on separate boxes;
     *   5. one frame of grace, so the swap replaces DOM that has painted
     *      its final pose with DOM that paints the identical pose.
     *
     * Everything here is event-driven and runs a handful of times per
     * state change — never per frame. Late is free; early is a glitch.
     */
    const armDemotion = (): void => {
      let cancelled = false;
      let grace = 0;
      const settle = () => {
        if (cancelled) return;
        if (root.dataset.emitting !== undefined) {
          emitReleasedRef.current = settle;
          return;
        }
        const running = root
          .getAnimations({ subtree: true })
          .filter((animation) => animation.playState === "running");
        if (running.length > 0) {
          void Promise.allSettled(
            running.map((animation) => animation.finished),
          ).then(() => {
            if (!cancelled) settle();
          });
          return;
        }
        grace = requestAnimationFrame(() => {
          if (cancelled) return;
          setMode("static");
        });
      };
      const onTransitionEnd = (event: TransitionEvent): void => {
        // The WELL is what settles now, and the property filter matters more
        // than it used to: the well also transitions `color`, so an untyped
        // listener would demote on the tint crossing rather than the pose's.
        if (event.target === well && event.propertyName === "transform") {
          settle();
        }
      };
      well.addEventListener("transitionend", onTransitionEnd);
      const fallback = window.setTimeout(
        settle,
        resolvedSettleMs(well) + DEMOTE_SETTLE_SLACK,
      );
      demotionRef.current = {
        cancel() {
          cancelled = true;
          well.removeEventListener("transitionend", onTransitionEnd);
          window.clearTimeout(fallback);
          if (grace !== 0) cancelAnimationFrame(grace);
        },
      };
    };

    // First paint in live mode, which means born RUNNING: the mode
    // initializer derives `static` from the same `state` this effect reads,
    // so a dot born settled never reaches here — it is static's business.
    // Nothing to cross from, so the full pose and the loops are seeded
    // directly — with the transition suppressed around the write. There is
    // nothing this could visibly transition FROM, so letting it fire buys
    // only a wasted style pass, and WebKit retains the finished
    // CSSTransition in getAnimations() forever — one zombie per dot,
    // iterated by the animation controller on every rendering update.
    // Whether it fires depends on whether anything flushed style between
    // the insertion and this effect, so the suppression is unconditional.
    if (previous === null) {
      well.style.transition = "none";
      well.style.transform = dotPose(1);
      flushStyle(well);
      well.style.transition = "";
      startLoops(0);
      return;
    }

    // Just promoted from static: the render dropped [data-static], whose
    // rules were carrying the pose, and the well holds no inline transform.
    // Seed the pose the static DOM was painting — suppressed, it IS that
    // pose — so the crossing below starts from exactly there.
    if (well.style.transform === "") {
      well.style.transition = "none";
      well.style.transform = dotPose(settledScaleFor(previous, size));
      flushStyle(well);
      well.style.transition = "";
    }

    if (previous === "running" && !isRunning) {
      // The breath's scale lives on the DOT; the well is standing at 1.
      const live = liveScale(dot);
      if (live !== null) {
        well.style.transition = "none";
        well.style.transform = dotPose(live);
      }
      delete root.dataset.breathing;
      // Flush the pin while the transition is suppressed. The dot falls back
      // to its base `scale(1)` in the same flush, so the PAINTED pose — well
      // times dot — is exactly what it was, and dropping the loop fires
      // nothing.
      flushStyle(well);
      well.style.transition = "";
      well.style.transform = dotPose(staticScale);
      releaseEmitter(root, ring, emitTimerRef, () =>
        emitReleasedRef.current?.(),
      );
      armDemotion();
      return;
    }

    if (previous !== "running" && isRunning) {
      // Coming the other way the settled pose is on the WELL, and the dot is
      // the one standing at 1.
      const live = liveScale(well);
      // Work resuming while the last settle's pulse is still in the air — the
      // ordinary way work resumes, since a pulse travels most of a cycle. The
      // ring is spoken for and cannot be restarted without cutting a pulse
      // that is entitled to finish, so the BREATH goes to the ring instead:
      // welded to the clock the flying pulse is already on ([P05]).
      const flying =
        root.dataset.emitting !== undefined && emitTimerRef.current !== null;
      const ringClock = flying ? breathClock(ring) : null;

      if (ringClock !== null) {
        // The welded phase is somewhere on the fall — the ring is past
        // ignition or it would not be flying — so the breath's pose there is
        // not the pose the settled dot is standing at. The WELL absorbs the
        // difference: pinned at the RATIO, it multiplies the breath's opening
        // pose back to exactly what was on screen, and then releases to 1 on
        // the settle transition. The eye sees the settled dot glide into a
        // breath that was already running at the right phase.
        const welded = Math.max(
          breathScaleAt(ringClock.phase, scaleMin, scaleMax),
          scaleMin,
        );
        well.style.transition = "none";
        well.style.transform = dotPose(
          live === null || welded <= 0 ? 1 : live / welded,
        );
        // `startLoops` resolves style itself, which is the flush this pin
        // needs — pin and gates land in one pass at the painted scale.
        startLoops(ringClock.phase);
        well.style.transition = "";
        well.style.transform = dotPose(1);
        return;
      }

      // The ring is free, so the breath takes its own phase: the one whose
      // pose the dot is already standing at. Hand the pose back to the dot
      // first — the well carried the settled scale while the glyph was still,
      // and leaving it at anything but 1 would multiply the two.
      well.style.transition = "none";
      well.style.transform = dotPose(1);
      startLoops(live === null ? 0 : breathPhaseFor(live, scaleMin, scaleMax));
      well.style.transition = "";
      return;
    }

    well.style.transform = dotPose(isRunning ? 1 : staticScale);
    if (!isRunning) armDemotion();
  }, [state, staticScale, scaleMin, scaleMax, mode, size]);

  React.useEffect(
    () => () => {
      if (emitTimerRef.current !== null)
        window.clearTimeout(emitTimerRef.current);
      demotionRef.current?.cancel();
      motionHoldRef.current?.();
      motionHoldRef.current = null;
      offscreenRef.current?.();
      offscreenRef.current = null;
    },
    [],
  );

  return (
    <span
      ref={setRootRef}
      data-slot="tug-progress-pulsing-dot"
      data-state={state}
      // Geometry only, and CSS's alone: the shape restates the dot's box and
      // touches nothing the controller below reads, so a change of shape is a
      // change of two custom properties mid-breath rather than a crossing.
      data-shape={shape === "dot" ? undefined : shape}
      data-static={mode === "static" ? "" : undefined}
      aria-hidden="true"
      style={rootStyle}
      className={cn(
        "tug-progress-pulsing-dot",
        disabled && "tug-progress-pulsing-dot-disabled",
        className,
      )}
    >
      {/* Each figure sits in a WELL that owns its position, its crossing pose
          and its tint, so the figure itself carries nothing but its keyframes
          — the one structure in which WebKit cannot demote the loop on
          account of a neighbouring transition. In static mode both wells are
          `display: contents` and the glyph is the three boxes it always was. */}
      <span ref={dotWellRef} className="tug-progress-pulsing-dot-dot-well">
        <span ref={dotRef} className="tug-progress-pulsing-dot-dot" />
      </span>
      {/* The emitted pulse. Its stroke opens as it travels, because a border on
          a scaled element paints at border × scale. */}
      <span ref={ringWellRef} className="tug-progress-pulsing-dot-ring-well">
        <span ref={ringRef} className="tug-progress-pulsing-dot-ring" />
      </span>
    </span>
  );
});
