#!/usr/bin/env bun
/**
 * third-party-notices — generate the "libraries shipped inside Tug.app" half
 * of `THIRD_PARTY_NOTICES.md` from the lockfiles, and check it.
 *
 *   bun scripts/third-party-notices.ts           # rewrite the generated half
 *   bun scripts/third-party-notices.ts --check   # fail on drift or a license outside the allow-list
 *
 * The file has two halves. Everything above MARKER is hand-written: the L21
 * entries for code and patterns adopted into this checkout, and the binaries
 * the bundle carries that no lockfile names (tmux and its libraries, fonts).
 * Everything below it is this script's output, and nothing else writes there.
 *
 * What ships, per tree:
 *   - `tugrust/Cargo.lock` — every crate a workspace member reaches through
 *     normal (not dev, not build) dependency edges on the macOS targets, read
 *     through `cargo metadata`.
 *   - `tugdeck/crates/Cargo.lock` — the same for the wasm crates, on
 *     `wasm32-unknown-unknown`; their output ships in the deck bundle.
 *   - `tugdeck/bun.lock` — the closure of `tugdeck/package.json`'s
 *     `dependencies`; its `devDependencies` are build tools and never ship.
 *   - `tugcode/bun.lock` — tugcode declares every package as a dev
 *     dependency, so its roots are the packages `tugcode/src` actually
 *     imports at runtime (type-only imports excluded); `bun build --compile`
 *     bundles exactly those.
 *   - `Package.resolved` — the SwiftPM pins, through the SWIFT table below.
 *
 * A license is read from each package's own manifest (`Cargo.toml` via cargo
 * metadata, `package.json` from node_modules), parsed as an SPDX expression,
 * and elected: an OR takes its first allowed alternative, an AND needs every
 * operand allowed. The allow-list is the keys of LICENSE_TEXTS — so admitting
 * a new license means writing its text here, which is the review L21 asks for.
 * Contract: [L21] in tuglaws/tuglaws.md, and the no-GPL rule [D171] rides.
 */
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..");
const NOTICES = join(ROOT, "THIRD_PARTY_NOTICES.md");
const MARKER =
  "<!-- Generated by scripts/third-party-notices.ts (`just notices`). Do not edit below this line. -->";

const MACOS_TARGETS = ["aarch64-apple-darwin", "x86_64-apple-darwin"];
const WASM_TARGETS = ["wasm32-unknown-unknown"];

/** The SwiftPM pins `Package.resolved` carries, keyed by identity. */
const SWIFT: Record<string, { name: string; license: string }> = {
  sparkle: { name: "Sparkle", license: "MIT" },
};

/**
 * npm packages whose `package.json` declares no license, keyed `name@version`,
 * each read off the package's own license file. A version bump drops out of
 * this table and fails the check until the new file is read again.
 */
const NPM_LICENSE_OVERRIDES: Record<string, string> = {
  "khroma@2.1.0": "MIT", // node_modules/khroma/license
};

/** Workspace-local import aliases in tugcode that are not npm packages. */
const LOCAL_IMPORT_PREFIXES = ["@tugproto/"];

/** The only SPDX exception admitted; it grants permissions and takes none. */
const ALLOWED_EXCEPTIONS = new Set(["LLVM-exception"]);

// ---------------------------------------------------------------------------
// License texts — the allow-list. Order is election preference for an OR.
// ---------------------------------------------------------------------------

const MIT_TEXT = `Copyright (c) <year> <copyright holders>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`;

// Apache-2.0 §4(a) requires recipients be given a copy of the License itself,
// so the full terms are reproduced, not the per-file header. Too long to sit
// inline; the file is the apache.org text as pdfjs-dist and sync_wrapper ship it.
const APACHE_TEXT = readFileSync(join(import.meta.dir, "third-party-licenses", "Apache-2.0.txt"), "utf8").trimEnd();

const BSD_DISCLAIMER = `THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.`;

const BSD2_TEXT = `Copyright (c) <year> <copyright holders>

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

${BSD_DISCLAIMER}`;

const BSD3_TEXT = `Copyright (c) <year> <copyright holders>

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

${BSD_DISCLAIMER}`;

const ISC_TEXT = `Copyright (c) <year> <copyright holders>

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.`;

const ZLIB_TEXT = `Copyright (c) <year> <copyright holders>

This software is provided 'as-is', without any express or implied
warranty. In no event will the authors be held liable for any damages
arising from the use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not
   claim that you wrote the original software. If you use this software
   in a product, an acknowledgment in the product documentation would be
   appreciated but is not required.
2. Altered source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.
3. This notice may not be removed or altered from any source distribution.`;

const UNICODE_TEXT = `UNICODE LICENSE V3

COPYRIGHT AND PERMISSION NOTICE

Copyright © 1991-2024 Unicode, Inc.

NOTICE TO USER: Carefully read the following legal agreement. BY
DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.

Permission is hereby granted, free of charge, to any person obtaining a
copy of data files and any associated documentation (the "Data Files") or
software and any associated documentation (the "Software") to deal in the
Data Files or Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, and/or sell
copies of the Data Files or Software, and to permit persons to whom the
Data Files or Software are furnished to do so, provided that either (a)
this copyright and permission notice appear with all copies of the Data
Files or Software, or (b) this copyright and permission notice appear in
associated Documentation.

THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
THIRD PARTY RIGHTS.

IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
FILES OR SOFTWARE.

Except as contained in this notice, the name of a copyright holder shall
not be used in advertising or otherwise to promote the sale, use or other
dealings in these Data Files or Software without prior written
authorization of the copyright holder.`;

const PUBLIC_DOMAIN_NOTE =
  "Dedicated to the public domain; no notice is required. Listed so the set of licenses the bundle carries is complete.";

const CDLA_TEXT = `Community Data License Agreement - Permissive - Version 2.0

1. Provision of the Data

1.1. A Data Recipient may use, modify, and share the Data made available by
Data Provider(s) under this agreement if that Data Recipient follows the terms
of this agreement.

1.2. This agreement does not impose any restriction on a Data Recipient's use,
modification, or sharing of any portions of the Data that are in the public
domain or that may be used, modified, or shared under any other legal
exception or limitation.

2. Conditions for Sharing Data

2.1. A Data Recipient may share Data, with or without modifications, so long
as the Data Recipient makes available the text of this agreement with the
shared Data.

3. No Restrictions on Results

3.1. This agreement does not impose any restriction or obligations with
respect to the use, modification, or sharing of Results.

4. No Warranty; Limitation of Liability

4.1. All Data Recipients receive the Data subject to the following terms:

THE DATA IS PROVIDED ON AN "AS IS" BASIS, WITHOUT REPRESENTATIONS, WARRANTIES
OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED INCLUDING, WITHOUT
LIMITATION, ANY WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT,
MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.

NO DATA PROVIDER SHALL HAVE ANY LIABILITY FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING WITHOUT
LIMITATION LOST PROFITS), HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
OTHERWISE) ARISING IN ANY WAY OUT OF THE DATA OR RESULTS, EVEN IF ADVISED OF
THE POSSIBILITY OF SUCH DAMAGES.

5. Definitions

5.1. "Data" means the material received by a Data Recipient under this
agreement.

5.2. "Data Provider" means any person who is the source of Data provided
under this agreement and in reliance on a Data Recipient's agreement to its
terms.

5.3. "Data Recipient" means any person who receives Data directly or
indirectly from a Data Provider and agrees to the terms of this agreement.

5.4. "Results" means any outcome obtained by computational analysis of Data,
including for example machine learning models and models' insights.`;

const MPL_TEXT = `This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.

The Source Code Form of each MPL-2.0 package listed above is available
at the repository named beside it.`;

/** SPDX id → the text reproduced once in the notices. Keys are the allow-list. */
const LICENSE_TEXTS: Record<string, string> = {
  MIT: MIT_TEXT,
  "Apache-2.0": APACHE_TEXT,
  "BSD-2-Clause": BSD2_TEXT,
  "BSD-3-Clause": BSD3_TEXT,
  ISC: ISC_TEXT,
  "0BSD": "Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted. No notice is required.",
  Zlib: ZLIB_TEXT,
  "Unicode-3.0": UNICODE_TEXT,
  "Unicode-DFS-2016": UNICODE_TEXT,
  "MPL-2.0": MPL_TEXT,
  "CDLA-Permissive-2.0": CDLA_TEXT,
  "CC0-1.0": PUBLIC_DOMAIN_NOTE,
  Unlicense: PUBLIC_DOMAIN_NOTE,
};

const ALLOWED = Object.keys(LICENSE_TEXTS);

// ---------------------------------------------------------------------------
// SPDX expressions
// ---------------------------------------------------------------------------

type Expr =
  | { op: "id"; id: string }
  | { op: "and" | "or"; args: Expr[] };

function parseSpdx(raw: string): Expr {
  // Old crates write `MIT/Apache-2.0` for an OR; normalise before tokenising.
  const tokens = raw.replace(/\//g, " OR ").match(/\(|\)|[^\s()]+/g) ?? [];
  let i = 0;
  const peek = () => tokens[i];
  function primary(): Expr {
    const t = tokens[i++];
    if (t === undefined) throw new Error(`unexpected end of license expression "${raw}"`);
    if (t === "(") {
      const e = or();
      if (tokens[i++] !== ")") throw new Error(`unbalanced parentheses in "${raw}"`);
      return e;
    }
    if (peek() === "WITH") {
      i++;
      const exception = tokens[i++];
      if (!ALLOWED_EXCEPTIONS.has(exception ?? "")) {
        throw new Error(`license exception "${exception}" in "${raw}" is not admitted`);
      }
    }
    return { op: "id", id: t };
  }
  function and(): Expr {
    const args = [primary()];
    while (peek() === "AND") {
      i++;
      args.push(primary());
    }
    return args.length === 1 ? args[0] : { op: "and", args };
  }
  function or(): Expr {
    const args = [and()];
    while (peek() === "OR") {
      i++;
      args.push(and());
    }
    return args.length === 1 ? args[0] : { op: "or", args };
  }
  const e = or();
  if (i !== tokens.length) throw new Error(`trailing tokens in license expression "${raw}"`);
  return e;
}

/** The license ids an expression is used under, or null when nothing allowed satisfies it. */
function elect(e: Expr): string[] | null {
  if (e.op === "id") return ALLOWED.includes(e.id) ? [e.id] : null;
  if (e.op === "and") {
    const all: string[] = [];
    for (const a of e.args) {
      const got = elect(a);
      if (got === null) return null;
      all.push(...got);
    }
    return all;
  }
  const options = e.args.map(elect).filter((x): x is string[] => x !== null);
  if (options.length === 0) return null;
  const rank = (ids: string[]) => Math.max(...ids.map((id) => ALLOWED.indexOf(id)));
  options.sort((a, b) => rank(a) - rank(b));
  return options[0];
}

// ---------------------------------------------------------------------------
// Inventory
// ---------------------------------------------------------------------------

interface Entry {
  name: string;
  version: string;
  license: string;
  repository: string;
}

interface Tree {
  title: string;
  source: string;
  entries: Entry[];
}

const problems: string[] = [];

function cleanRepo(raw: unknown): string {
  let url = "";
  if (typeof raw === "string") url = raw;
  else if (raw && typeof raw === "object" && typeof (raw as { url?: unknown }).url === "string") {
    url = (raw as { url: string }).url;
  }
  url = url
    .trim()
    .replace(/^git\+/, "")
    .replace(/^git:\/\//, "https://")
    .replace(/^ssh:\/\/git@/, "https://")
    .replace(/^git@github\.com:/, "https://github.com/")
    .replace(/\.git$/, "")
    .replace(/\/$/, "");
  if (/^github:/.test(url)) url = `https://github.com/${url.slice("github:".length)}`;
  else if (/^[\w.-]+\/[\w.-]+$/.test(url)) url = `https://github.com/${url}`;
  return url;
}

function cargoTree(dir: string, targets: string[], title: string): Tree {
  const args = ["metadata", "--format-version", "1", "--locked"];
  for (const t of targets) args.push("--filter-platform", t);
  const proc = Bun.spawnSync(["cargo", ...args], { cwd: join(ROOT, dir), stdout: "pipe", stderr: "pipe" });
  if (proc.exitCode !== 0) {
    throw new Error(`cargo metadata failed in ${dir}:\n${proc.stderr.toString()}`);
  }
  const meta = JSON.parse(proc.stdout.toString()) as {
    packages: { id: string; name: string; version: string; license: string | null; repository: string | null; source: string | null }[];
    workspace_members: string[];
    resolve: { nodes: { id: string; deps: { pkg: string; dep_kinds: { kind: string | null }[] }[] }[] };
  };
  const byId = new Map(meta.packages.map((p) => [p.id, p]));
  const nodes = new Map(meta.resolve.nodes.map((n) => [n.id, n]));
  const members = new Set(meta.workspace_members);
  const seen = new Set<string>();
  const stack = [...members];
  while (stack.length > 0) {
    const id = stack.pop()!;
    if (seen.has(id)) continue;
    seen.add(id);
    for (const d of nodes.get(id)?.deps ?? []) {
      if (d.dep_kinds.some((k) => k.kind === null)) stack.push(d.pkg);
    }
  }
  const entries: Entry[] = [];
  for (const id of seen) {
    if (members.has(id)) continue;
    const p = byId.get(id)!;
    if (p.source === null) {
      problems.push(`${dir}: ${p.name} is a path dependency outside the workspace; it has no lockfile identity to list`);
      continue;
    }
    entries.push({ name: p.name, version: p.version, license: p.license ?? "", repository: cleanRepo(p.repository) });
  }
  return { title, source: `${dir}/Cargo.lock`, entries };
}

/** bun.lock is JSON with trailing commas. */
function readBunLock(path: string): {
  workspaces: Record<string, { dependencies?: Record<string, string> }>;
  packages: Record<string, [string, string, BunMeta?, string?]>;
} {
  const text = readFileSync(path, "utf8").replace(/,(\s*[}\]])/g, "$1");
  return JSON.parse(text);
}

interface BunMeta {
  dependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
  optionalPeers?: string[];
}

function bunTree(dir: string, roots: string[], title: string): Tree {
  const lock = readBunLock(join(ROOT, dir, "bun.lock"));
  const pkgs = lock.packages;
  const nameOf = (key: string) => {
    const spec = pkgs[key][0];
    return spec.slice(0, spec.lastIndexOf("@"));
  };
  const parentOf = (key: string) => {
    const name = nameOf(key);
    return key.length > name.length ? key.slice(0, key.length - name.length - 1) : null;
  };
  /** Node's resolution, expressed over bun.lock's nested keys. */
  const resolve = (from: string | null, dep: string): string | null => {
    for (let k = from; k !== null; k = parentOf(k)) {
      if (pkgs[`${k}/${dep}`]) return `${k}/${dep}`;
    }
    return pkgs[dep] ? dep : null;
  };
  const modulePath = (key: string): string => {
    const parent = parentOf(key);
    const name = nameOf(key);
    return parent === null ? join("node_modules", name) : join(modulePath(parent), "node_modules", name);
  };
  const seen = new Set<string>();
  const stack: string[] = [];
  for (const r of roots) {
    const key = resolve(null, r);
    if (key === null) problems.push(`${dir}: root "${r}" is not in bun.lock`);
    else stack.push(key);
  }
  while (stack.length > 0) {
    const key = stack.pop()!;
    if (seen.has(key)) continue;
    seen.add(key);
    const meta = pkgs[key][2];
    const optionalPeers = new Set(meta?.optionalPeers ?? []);
    // optionalDependencies are left out: in these trees they are per-platform
    // native binaries for Node (pdfjs-dist's canvas) and type packages, and
    // neither reaches a browser bundle or a `bun build --compile` output.
    const deps = [
      ...Object.keys(meta?.dependencies ?? {}),
      ...Object.keys(meta?.peerDependencies ?? {}).filter((d) => !optionalPeers.has(d)),
    ];
    for (const d of deps) {
      const target = resolve(key, d);
      if (target === null) {
        problems.push(`${dir}: ${nameOf(key)} depends on "${d}", which bun.lock does not resolve`);
        continue;
      }
      stack.push(target);
    }
  }

  const entries: Entry[] = [];
  for (const key of seen) {
    const spec = pkgs[key][0];
    const at = spec.lastIndexOf("@");
    const name = spec.slice(0, at);
    const version = spec.slice(at + 1);
    const manifestPath = join(ROOT, dir, modulePath(key), "package.json");
    if (!existsSync(manifestPath)) {
      problems.push(`${dir}: ${relative(ROOT, manifestPath)} is missing — run \`bun install\` in ${dir}`);
      continue;
    }
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as {
      license?: string | { type?: string };
      licenses?: { type?: string }[];
      repository?: unknown;
      version?: string;
    };
    let license = "";
    if (typeof manifest.license === "string") license = manifest.license;
    else if (manifest.license?.type) license = manifest.license.type;
    else if (manifest.licenses?.length) license = manifest.licenses.map((l) => l.type).join(" OR ");
    if (license === "") license = NPM_LICENSE_OVERRIDES[`${name}@${version}`] ?? "";
    // The version is the lockfile's and the license is node_modules'; a stale
    // install would put the old package's license beside the new version.
    if (manifest.version !== version) {
      problems.push(
        `${dir}: ${relative(ROOT, manifestPath)} is ${manifest.version}, bun.lock says ${version} — run \`bun install\` in ${dir}`,
      );
      continue;
    }
    entries.push({ name, version, license, repository: cleanRepo(manifest.repository) });
  }
  return { title, source: `${dir}/bun.lock`, entries };
}

/** The npm packages `dir/src` imports at runtime, outside tests. */
function importedPackages(dir: string): string[] {
  const transpiler = new Bun.Transpiler({ loader: "ts" });
  const found = new Set<string>();
  const walk = (d: string) => {
    for (const name of readdirSync(d)) {
      const p = join(d, name);
      if (statSync(p).isDirectory()) {
        if (name !== "__tests__") walk(p);
      } else if (/\.tsx?$/.test(name) && !/\.test\.tsx?$/.test(name)) {
        const source = readFileSync(p, "utf8").replace(/^#!.*/, "");
        for (const imp of transpiler.scanImports(source)) {
          const spec = imp.path;
          if (spec.startsWith(".") || spec.startsWith("/") || /^(node|bun):/.test(spec) || spec === "bun") continue;
          if (LOCAL_IMPORT_PREFIXES.some((pre) => spec.startsWith(pre))) continue;
          const parts = spec.split("/");
          found.add(spec.startsWith("@") ? `${parts[0]}/${parts[1]}` : parts[0]);
        }
      }
    }
  };
  walk(join(ROOT, dir, "src"));
  return [...found].sort();
}

function swiftTree(): Tree {
  const rel = "tugapp/Tug.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved";
  const resolved = JSON.parse(readFileSync(join(ROOT, rel), "utf8")) as {
    pins: { identity: string; location: string; state: { version?: string; revision: string } }[];
  };
  const entries: Entry[] = [];
  for (const pin of resolved.pins) {
    const known = SWIFT[pin.identity];
    if (!known) {
      problems.push(`${rel}: SwiftPM pin "${pin.identity}" has no entry in the SWIFT table of scripts/third-party-notices.ts`);
      continue;
    }
    entries.push({
      name: known.name,
      version: pin.state.version ?? pin.state.revision.slice(0, 12),
      license: known.license,
      repository: cleanRepo(pin.location),
    });
  }
  return { title: "Swift packages linked into Tug.app", source: rel, entries };
}

// ---------------------------------------------------------------------------
// Render
// ---------------------------------------------------------------------------

function render(trees: Tree[]): string {
  const used = new Set<string>();
  const lines: string[] = [];
  lines.push(MARKER, "");
  lines.push("## Libraries shipped inside Tug.app");
  lines.push("");
  lines.push(
    "Every third-party library the bundle carries, generated from the lockfiles named under each heading. Each row gives the license the package declares; the full text of each license is reproduced once, at the end, rather than once per package. The copyright holders for each package are named in the repository listed beside it.",
  );
  for (const tree of trees) {
    const sorted = [...tree.entries].sort((a, b) =>
      a.name === b.name ? Bun.semver.order(a.version, b.version) : a.name < b.name ? -1 : 1,
    );
    lines.push("", "---", "", `### ${tree.title}`, "", `From \`${tree.source}\` — ${sorted.length} ${sorted.length === 1 ? "package" : "packages"}.`, "");
    lines.push("| Package | Version | License | Repository |", "|---|---|---|---|");
    for (const e of sorted) {
      let elected: string[] | null = null;
      if (e.license === "") {
        problems.push(`${tree.source}: ${e.name} ${e.version} declares no license`);
      } else {
        try {
          elected = elect(parseSpdx(e.license));
        } catch (err) {
          problems.push(`${tree.source}: ${e.name} ${e.version}: ${(err as Error).message}`);
        }
        if (elected === null) {
          problems.push(
            `${tree.source}: ${e.name} ${e.version} is licensed "${e.license}", outside the allow-list (${ALLOWED.join(", ")})`,
          );
        }
      }
      for (const id of elected ?? []) used.add(id);
      const repo = e.repository === "" ? "—" : e.repository;
      lines.push(`| ${e.name} | ${e.version} | ${e.license.replace(/\|/g, "\\|") || "—"} | ${repo} |`);
    }
  }
  lines.push("", "---", "", "### License texts", "");
  lines.push(
    "One copy of each license the packages above are used under. Where a package offers a choice, it is used under the first of these that it offers.",
  );
  const seenText = new Set<string>();
  for (const id of ALLOWED) {
    if (!used.has(id) || seenText.has(LICENSE_TEXTS[id])) continue;
    seenText.add(LICENSE_TEXTS[id]);
    const aliases = ALLOWED.filter((a) => used.has(a) && LICENSE_TEXTS[a] === LICENSE_TEXTS[id]);
    lines.push("", `#### ${aliases.join(", ")}`, "", "```", LICENSE_TEXTS[id], "```");
  }
  return `${lines.join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const check = process.argv.includes("--check");

const tugdeckManifest = JSON.parse(readFileSync(join(ROOT, "tugdeck/package.json"), "utf8")) as {
  dependencies?: Record<string, string>;
};
const trees: Tree[] = [
  cargoTree("tugrust", MACOS_TARGETS, "Rust crates compiled into tugcast, tugtool, and the other tugrust binaries"),
  cargoTree("tugdeck/crates", WASM_TARGETS, "Rust crates compiled to WebAssembly for tugdeck"),
  bunTree("tugdeck", Object.keys(tugdeckManifest.dependencies ?? {}), "npm packages bundled into tugdeck"),
  bunTree("tugcode", importedPackages("tugcode"), "npm packages compiled into tugcode"),
  swiftTree(),
];
const generated = render(trees);

const current = readFileSync(NOTICES, "utf8");
const at = current.indexOf(MARKER);
const handWritten = at === -1 ? `${current.trimEnd()}\n\n---\n\n` : current.slice(0, at);
const next = handWritten + generated;

if (problems.length > 0) {
  for (const p of problems) console.error(`third-party-notices: ${p}`);
  process.exit(1);
}

if (check) {
  if (at === -1) {
    console.error("third-party-notices: THIRD_PARTY_NOTICES.md has no generated section — run `just notices`");
    process.exit(1);
  }
  if (next !== current) {
    const want = generated.split("\n");
    const have = current.slice(at).split("\n");
    // No differing line within `want` means the committed file runs longer.
    const differs = want.findIndex((l, i) => l !== have[i]);
    const line = differs === -1 ? want.length : differs;
    const lineNo = current.slice(0, at).split("\n").length + line;
    console.error(`third-party-notices: THIRD_PARTY_NOTICES.md:${lineNo} differs from the lockfiles — run \`just notices\``);
    console.error(`  committed: ${have[line] ?? "(end of file)"}`);
    console.error(`  generated: ${want[line] ?? "(end of file)"}`);
    process.exit(1);
  }
  const count = trees.reduce((n, t) => n + t.entries.length, 0);
  console.log(`third-party-notices: ${count} shipped packages, all permissive, notices current`);
} else {
  writeFileSync(NOTICES, next);
  console.log(`third-party-notices: wrote ${relative(ROOT, NOTICES)}`);
}
